# Generated by Django 4.2 on 2023-04-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('name', models.CharField(default='', max_length=32)),
                ('number', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
