# Generated by Django 4.2 on 2023-04-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
